import { notFound } from "next/navigation";

import { IdeaPicker } from "@/components/IdeaPicker";
import { ErrorState, GeminiBadge } from "@/components/ui";
import { ApiError, api, type IdeaSet } from "@/lib/api";

export const metadata = { title: "Choose your project" };

/** Server Component: the ideas are fetched on the server, picking is client-side. */
export default async function IdeasPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  let ideaSet: IdeaSet;
  try {
    ideaSet = await api.get<IdeaSet>(`/ideas/${id}`);
  } catch (cause: unknown) {
    if (cause instanceof ApiError && cause.status === 404) notFound();
    return (
      <ErrorState
        title="Could not load your ideas"
        message={cause instanceof Error ? cause.message : "Unknown error"}
      />
    );
  }

  return (
    <div className="flex flex-col gap-8">
      <header className="flex flex-col gap-3">
        <h1 className="text-2xl font-bold tracking-tight text-fg sm:text-3xl">
          Three ideas for you
        </h1>
        <p className="max-w-2xl text-sm text-muted">
          Based on your interests in <strong className="text-fg">{ideaSet.interests}</strong>{" "}
          and your skills in <strong className="text-fg">{ideaSet.skills}</strong>. Choose
          one and we will build its roadmap.
        </p>
        <GeminiBadge label="Ideas generated by Gemini" />
      </header>

      <IdeaPicker ideas={ideaSet.ideas} />
    </div>
  );
}
