import { notFound } from "next/navigation";

import { ComparisonBlock } from "@/components/ComparisonBlock";
import { FallbackBanner } from "@/components/FallbackBanner";
import { IdeaPicker } from "@/components/IdeaPicker";
import { ErrorState, GeminiBadge } from "@/components/ui";
import { ApiError, api, type IdeaSet } from "@/lib/api";

export const metadata = { title: "Choose your project" };

/** Server Component: the ideas are fetched on the server, picking is client-side. */
export default async function IdeasPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  let ideaSet: IdeaSet;
  try {
    ideaSet = await api.get<IdeaSet>(`/ideas/${id}`);
  } catch (cause: unknown) {
    if (cause instanceof ApiError && cause.status === 404) notFound();
    return (
      <ErrorState
        title="Could not load your ideas"
        message={cause instanceof Error ? cause.message : "Unknown error"}
      />
    );
  }

  return (
    <div className="flex flex-col gap-8">
      <header className="flex flex-col gap-3">
        <p className="font-mono text-xs uppercase tracking-widest text-amber">Step 2 of 3</p>
        <h1 className="font-display text-2xl font-bold tracking-tight text-ink sm:text-4xl">
          Three ideas for you
        </h1>
        <p className="max-w-2xl text-sm text-ink-muted">
          Based on your interests in <strong className="text-ink">{ideaSet.interests}</strong>{" "}
          and your skills in <strong className="text-ink">{ideaSet.skills}</strong>. Choose
          one and we will build its roadmap.
        </p>
        <GeminiBadge label="Ideas generated by Gemini" />
      </header>

      {ideaSet.used_fallback ? <FallbackBanner what="these ideas" /> : null}

      <IdeaPicker
        ideas={ideaSet.ideas}
        interests={ideaSet.interests}
        skills={ideaSet.skills}
      />

      {ideaSet.ideas.length > 0 ? (
        <ComparisonBlock idea={ideaSet.ideas[0]!} stepCount={12} />
      ) : null}
    </div>
  );
}
